In [1]:
import numpy as np

one_arr=np.array([[1,1],[0,0],[1,1]])
zero_arr=np.abs(one_arr-1)
a=np.array([one_arr,zero_arr])

arr=np.ones((64,64,3))
l=[1,0,1]


In [9]:
def weight_method(X, Y, nclasses):
    _Y = np.argmax(Y, axis=4)
    counts = np.array([(_Y == label).sum() for label in range(nclasses)])
    counts = np.cbrt(np.where(counts != 0, counts, 1))
    Y = Y * 1e0 / counts
    return Y

In [11]:
arr=np.random.randint(5,size=(2,8,8,4,2))



(2, 8, 8, 4, 2)

In [21]:
_Y=np.argmax(arr,axis=4)
counts = np.array([(_Y == label).sum() for label in range(2)])
counts = np.cbrt(np.where(counts != 0, counts, 1))

In [24]:
arr * 1e0

array([[[[[2., 4.],
          [3., 1.],
          [1., 1.],
          [1., 0.]],

         [[1., 4.],
          [0., 3.],
          [2., 2.],
          [1., 3.]],

         [[2., 0.],
          [4., 4.],
          [1., 1.],
          [1., 0.]],

         ...,

         [[2., 4.],
          [2., 0.],
          [1., 0.],
          [0., 1.]],

         [[2., 4.],
          [0., 4.],
          [2., 1.],
          [4., 0.]],

         [[0., 0.],
          [2., 2.],
          [4., 1.],
          [3., 0.]]],


        [[[1., 1.],
          [1., 2.],
          [2., 2.],
          [2., 1.]],

         [[3., 4.],
          [0., 4.],
          [1., 3.],
          [1., 1.]],

         [[1., 0.],
          [4., 3.],
          [3., 4.],
          [1., 1.]],

         ...,

         [[0., 1.],
          [4., 2.],
          [0., 1.],
          [0., 0.]],

         [[1., 4.],
          [2., 1.],
          [3., 1.],
          [1., 1.]],

         [[0., 4.],
          [0., 4.],
          [3., 4.],
      

In [22]:
counts


array([6.67194027, 5.99072641])

In [14]:
weight_method(arr,arr,2)[...,1]

array([[[[0.66769866, 0.16692467, 0.16692467, 0.        ],
         [0.66769866, 0.500774  , 0.33384933, 0.500774  ],
         [0.        , 0.66769866, 0.16692467, 0.        ],
         [0.16692467, 0.16692467, 0.16692467, 0.33384933],
         [0.500774  , 0.33384933, 0.500774  , 0.16692467],
         [0.66769866, 0.        , 0.        , 0.16692467],
         [0.66769866, 0.66769866, 0.16692467, 0.        ],
         [0.        , 0.33384933, 0.16692467, 0.        ]],

        [[0.16692467, 0.33384933, 0.33384933, 0.16692467],
         [0.66769866, 0.66769866, 0.500774  , 0.16692467],
         [0.        , 0.500774  , 0.66769866, 0.16692467],
         [0.        , 0.        , 0.500774  , 0.        ],
         [0.66769866, 0.33384933, 0.        , 0.33384933],
         [0.16692467, 0.33384933, 0.16692467, 0.        ],
         [0.66769866, 0.16692467, 0.16692467, 0.16692467],
         [0.66769866, 0.66769866, 0.66769866, 0.66769866]],

        [[0.500774  , 0.66769866, 0.16692467, 0.6676

In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv3D, Cropping3D, Conv3DTranspose, MaxPool3D, concatenate, BatchNormalization, Dropout, Activation

class Test_Network(Model):
    def __init__(self,input_shape,nclass):
        x = Input(shape=input_shape)
#         y = Conv3D(nclass,(1,1,1),activation='softmax',padding='same')(x)
        y = Conv3D(nclass,(1,1,1),activation='sigmoid',padding='same')(x)
        
#         x=Activation('relu')(y)
        
        super(Test_Network,self).__init__(inputs=x,outputs=y)
        


In [4]:
# del model
model=Test_Network((96,96,32,1),1)
print(model.output_shape)

(None, 96, 96, 32, 1)
